add_subdirectory(unit/core)
add_subdirectory(unit/ipc)
add_subdirectory(unit/service)
add_subdirectory(unit/package)

add_subdirectory(integration/ipc)
add_subdirectory(integration/rpc)
add_subdirectory(integration/supervisor)
add_subdirectory(integration/app_manager)
add_subdirectory(integration/arm64)

add_subdirectory(unit/osidlc)
add_subdirectory(generated/echo)
