add_subdirectory(unit/core)
add_subdirectory(unit/ipc)
add_subdirectory(unit/service)
add_subdirectory(unit/package)
add_subdirectory(unit/app)
add_subdirectory(unit/storage)
add_subdirectory(unit/keys)
add_subdirectory(unit/display)
add_subdirectory(unit/ui)

add_subdirectory(integration/ipc)
add_subdirectory(integration/rpc)
add_subdirectory(integration/supervisor)
add_subdirectory(integration/app_manager)
add_subdirectory(integration/storage)
add_subdirectory(integration/keys)
add_subdirectory(integration/display)
add_subdirectory(integration/arm64)

add_subdirectory(unit/osidlc)
add_subdirectory(generated/echo)
