#include <array>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <os/core/error.hpp>
#include <os/core/span.hpp>
#include <os/ipc/constants.hpp>
#include <os/ipc/decoder.hpp>
#include <os/ipc/encoder.hpp>
#include <os/ipc/wire.hpp>
namespace {template <std::size_t N> os::core::ByteSpan bytes(const std::array<std::uint8_t,N>& input){return {reinterpret_cast<const std::byte*>(input.data()),input.size()};}}
int main(){using namespace os; const ipc::WireHeaderV1 header{.flags=ipc::flag_value(ipc::WireFlag::request),.service_id=core::ServiceId{0x0000F001U},.operation_id=1U,.request_id=core::RequestId{0x0102030405060708ULL},.payload_size=5U,.handle_count=0U,.payload_checksum=0U}; std::array<std::byte,ipc::wire_header_v1_size> storage{}; ipc::Encoder encoder{storage}; assert(ipc::encode_wire_header_v1(encoder,header)); assert(encoder.written().size()==ipc::wire_header_v1_size); constexpr std::array<std::uint8_t,ipc::wire_header_v1_size> golden{0x4F,0x53,0x49,0x50,0x28,0x00,0x01,0x00,0x01,0x00,0x00,0x00,0x01,0xF0,0x00,0x00,0x01,0x00,0x00,0x00,0x08,0x07,0x06,0x05,0x04,0x03,0x02,0x01,0x05,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00}; for(std::size_t i=0;i<golden.size();++i) assert(std::to_integer<std::uint8_t>(storage[i])==golden[i]); ipc::Decoder decoder{storage};const auto decoded_result=ipc::decode_wire_header_v1(decoder);assert(decoded_result);assert(decoded_result.value()==header);assert(decoder.require_end());auto bad_magic=golden;bad_magic[0]=0x00;ipc::Decoder bad_magic_decoder{bytes(bad_magic)};assert(!ipc::decode_wire_header_v1(bad_magic_decoder));auto bad_version=golden;bad_version[6]=0x02;ipc::Decoder bad_version_decoder{bytes(bad_version)};const auto bad_version_result=ipc::decode_wire_header_v1(bad_version_decoder);assert(!bad_version_result);assert(bad_version_result.error()==core::make_error(core::ErrorDomain::ipc,ipc::errors::unsupported_version));auto invalid_flags=golden;invalid_flags[8]=0x03;ipc::Decoder invalid_flags_decoder{bytes(invalid_flags)};assert(!ipc::decode_wire_header_v1(invalid_flags_decoder));auto oversized_payload=golden;oversized_payload[28]=0x01;oversized_payload[29]=0x00;oversized_payload[30]=0x01;oversized_payload[31]=0x00;ipc::Decoder oversized_decoder{bytes(oversized_payload)};const auto oversized_result=ipc::decode_wire_header_v1(oversized_decoder);assert(!oversized_result);assert(oversized_result.error()==core::make_error(core::ErrorDomain::ipc,ipc::errors::oversized_message));auto reserved_nonzero=golden;reserved_nonzero[34]=0x01;ipc::Decoder reserved_decoder{bytes(reserved_nonzero)};assert(!ipc::decode_wire_header_v1(reserved_decoder));const ipc::WireHeaderV1 handles_without_flag{.flags=ipc::flag_value(ipc::WireFlag::request),.service_id=core::ServiceId{1U},.operation_id=1U,.request_id=core::RequestId{1U},.payload_size=0U,.handle_count=1U,.payload_checksum=0U};ipc::Encoder bad_flag_encoder{storage};assert(!ipc::encode_wire_header_v1(bad_flag_encoder,handles_without_flag));return 0;}
